inherit_gem:
  rubocop-rails-omakase: rubocop.yml

require:
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInMultilineCall: true
  AllowParenthesesInChaining: true
  AllowParenthesesInCamelCaseMethod: true
  AllowParenthesesInStringInterpolation: true

Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

RSpec/DescribedClass:
  EnforcedStyle: explicit
RSpec/NamedSubject:
  Enabled: true
RSpec/ImplicitSubject:
  EnforcedStyle: disallow
RSpec/ExampleLength:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false

FactoryBot/ConsistentParenthesesStyle:
  Enabled: false
