inherit_gem:
  rubocop-rails-omakase: rubocop.yml

require:
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

# No strict comment rule.
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false

# Fewer but necessary parentheses.
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInMultilineCall: true
  AllowParenthesesInChaining: true
  AllowParenthesesInCamelCaseMethod: true
  AllowParenthesesInStringInterpolation: true
FactoryBot/ConsistentParenthesesStyle:
  Enabled: false

# Namespace::Class is more readable.
Style/ClassAndModuleChildren:
  EnforcedStyle: compact

# Write code as long as we need.
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

# More readable spec.
RSpec/DescribedClass:
  EnforcedStyle: explicit
RSpec/NamedSubject:
  Enabled: true
RSpec/ImplicitSubject:
  EnforcedStyle: disallow
RSpec/ExampleLength:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false

# More convenient mock and stub.
RSpec/ExpectInHook:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
