require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-capybara

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

# No strict comment rule.
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

# Fewer but necessary parentheses.
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInMultilineCall: true
  AllowParenthesesInChaining: true
  AllowParenthesesInCamelCaseMethod: true
  AllowParenthesesInStringInterpolation: true
FactoryBot/ConsistentParenthesesStyle:
  Enabled: false

# Namespace::Class is more readable.
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - "config/application.rb"

# Write code as long as we need.
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

# Use reduce(:+) to join html elements.
Performance/Sum:
  Exclude:
    - "app/helpers/*.rb"

# More readable spec.
RSpec/DescribedClass:
  EnforcedStyle: explicit
RSpec/NamedSubject:
  Enabled: true
  Exclude:
    - "spec/support/*.rb"
RSpec/ImplicitSubject:
  EnforcedStyle: disallow
RSpec/ExampleLength:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false

# More convenient mock and stub.
RSpec/ExpectInHook:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
